model_name: "TransE"
datasets:
  - dataset: "freebase15k_237"
    parameters:
      learning_rate: 1.0
      l1_flag: True
      hidden_size: 200
      batch_size: 2560
      epochs: 1000
      margin: 5.00
      optimizer: "sgd"
      sampling: "bern"
      neg_rate: 1

  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.01
      l1_flag: True
      hidden_size: 50
      batch_size: 128
      epochs: 1000
      margin: 1.00
      optimizer: "sgd"
      sampling: "bern"
      neg_rate: 1

  - dataset: "wordnet18"
    parameters:
      learning_rate: 0.01
      l1_flag: True
      hidden_size: 20
      batch_size: 128
      epochs: 1000
      margin: 2.00
      optimizer: "sgd"
      sampling: "uniform"
      neg_rate: 1